### ISSUE TITLE
DEIM: matrix B non invertible

### ISSUE THREAD

**Issue by romainhild** [feelpp/feelpp#1012]
At the last iteration, the interpolation point is the same than the previous iteration, which leads to have the same two lines in the matrix and so it is not invertible.

**Comment by jbwahl** [comment]
This issue is actually a bug, regarding the deim algorithm this can not append because the approximation is always exact on the previous interpolation points.
I think this was related to the modification of the `operator()` for the matrix PETSc. Commit f1095709f3ec1067266050e84e7fe3537bcb820d should fix the bug. 
@romainhild can you check and close issue if it's ok for you ?

**Comment by jbwahl** [comment]
The problem actually seems to come from round-off error. Working on it...

**Comment by jbwahl** [comment]
@romainhild can you confirm we can close ?
