### ISSUE TITLE
OpenModelica cmake detection

### ISSUE THREAD

**Issue by lsala** [feelpp/feelpp#1085]
We would like to use OpenModelica within in Feel++ via the API.
We need first to add the cmake module to detect the libraries of OpenModelica.

We need it for the coupling between 3d and 0d in hdg applications.
It would be interesting also for other users to solve ODEs.

**Comment by lsala** [comment]
@jbwahl is it possible to test a model? What do you mean with "simple" ?

**Comment by jbwahl** [comment]
@lsala We use the OpenModelica model through the FMI standard. 
When you convert an OpenModelica model into an FMU model, you have to choose between two formats : 
- Co-Simulation (CS): model with embedded solver 
- Model Exchange (ME): model with no solver, we have to manage the initialization, the incrementation of the variables. We also have to provide a solver (for instance Euler Algorithm).

The CS format is obviously more convenient but is still in development. It works very well for simple models (also in Feel++) but since it is not totally stable yet it might not work very well for complex models. 
For now, only CS format is supported in Feel.


In Feel++, the cmake macro `add_ommodel` has an option to choose if you want to convert you OM model into a CS or ME FMU.
See `https://github.com/feelpp/feelpp/tree/feature/omc/testsuite/feelfmi` for an example.
