### ISSUE TITLE
SER should assemble the model after each EIM offline step

### ISSUE THREAD

**Issue by romainhild** [feelpp/feelpp#1130]
https://github.com/feelpp/feelpp/blob/39e19fdb7eacb7dc9822c69ac9cf7d8067b0682c/feel/feelcrb/ser.hpp#L134-L138
Here we should add `model->assemble()` so that the model can takes advantages of each new basis of EIM.
The same thing happens if the model uses more than one EIM.

What do you think @jbwahl ?

**Comment by jbwahl** [comment]
@romainhild I don't get your point. In this loop, EIM will add some basis vectors to improve its approximation. The EIM basis and the RB (for NL problem) is taken into account during the greedy selection.
You don't need to reassemble the model at this moment since the resolution does not use the affine approximation of the model but only `the solve()` function.
May I have missed something?

**Comment by romainhild** [comment]
When you use SER, you don't want EIM to use the `solve` function but the RB approximation.

**Comment by jbwahl** [comment]
why ?

**Comment by jbwahl** [comment]
You use the RB approximation in the greedy algorithm to chose the best fit. But at the end, you use the `solve` function to actually evaluate the new basis vector.
Anyway, I still don't get your point about the call of `model->assemble()`?

**Comment by romainhild** [comment]
say you have the following in you `computeBetaQm(mu)` function:
```c++
auto eimBeta = eim->beta(mu);
for(int m = 0; m < eim->mMax(); ++m)
  M_betaAqm[q][m] = eimBeta[m];
```
if you don't resize your vector of coefficients, and reassemble your matrices, you will have a segmentation fault at some point.

**Comment by jbwahl** [comment]
Well, now I see an issue... 
The call of `computeBetaQm` is only supposed to appear in the online RB resolution. But at this point, you don't want to use the new EIM basis vectors (if there are some) because you don't have the corresponding reduced matrices and vectors. 
So, I see two solutions : 
- you call in the loop `model->assemble()` and `crb->buildRbMatrix()` so you really use the new EIM basis vector
- you just change your `computeBetaQm` : 
```
auto eimBeta = eim->beta(mu);
M_betaAqm[q].resize(eim->mMax());
for(int m = 0; m < eim->mMax(); ++m)
  M_betaAqm[q][m] = eimBeta[m];
```

**Comment by romainhild** [comment]
yes indeed you would also need to call buildRbMatrix.
I think that the best would be to use the new EIM basis, no?

**Comment by jbwahl** [comment]
It is not a real issue when you only have one EIM, because we usually don't use the r-adaptation and so the next RB is built with all the EIM basis. 
It may have an interest when you have multiple EIM and when you don't want to use multiple levels in SER. 
The call of `assembleRbMatrix` also has a significant cost and should not be done if not necessary. The best options would be to detect in the online RB resolution if an EIM has changed and update structures if necessary. 

Anyway, I think we can do the modifications but with an option and then compare if there is a significant interest.

**Comment by romainhild** [comment]
Yes maybe you're right, it would too costly to rebuild everything after each EIM.
The best option could be to leave it as it is, and just be careful when using SER with multiple EIMs to not overflow the vector  of coefficients with something like what you propose:
```c++
auto eimBeta = eim->beta(mu);
auto mMax = std::min<int>(eimBeta->size(), M_betaAqm[q].size() );
for( int m = 0; m < mMax; ++m )
  M_betaAqm[q][m] = eimBeta[m];
```
This way you still have the same size between the coefficients and the vectors/matrices.
