### ISSUE TITLE
Missing link on Feel++ book on how to Compile Boost C++ library

### ISSUE THREAD

**Issue by lberti** [feelpp/feelpp#1141]
I was trying to install Feel++ in my computer but it's Ubuntu 16.04 and it has the following problem, already reported in the webpage. The link on how to recompile Boost is not working.

"We are unfortunately stung by the ABI change in GCC 6 when using clang. You need to recompile the Boost C++ libraries to be able to use clang, see the section in the Annexes on Compiling Boost."

**Comment by gdolle** [comment]
Hi @lberti,

Here you have the documentation on how to compile boost,
https://www.boost.org/doc/libs/1_66_0/more/getting_started/unix-variants.html

you can have a look at how we build boost for Feel++ on our ubuntu-16.04 docker images:
https://github.com/feelpp/docker/blob/2b53fc9ab1a730327b6f52ed4d06e691d6d36cc8/feelpp-env/Dockerfile-boost

Currently this issue is documentation related, I move this issue in the appropriate repository and close this one.

NB: We are currently moving/updating the documentation to this http://docs.feelpp.org don't hesitate to give us feedback.

**Comment by gdolle** [comment]
Issue moved to [feelpp/book.feelpp.org #66](https://github.com/feelpp/book.feelpp.org/issues/66) via [**ZenHub**](https://www.zenhub.com/)

**Comment by prudhomm** [comment]
Actually I wrote some docs about that. But it probably got lost in the transfer to antora.
I think it was in the FAQ section
