### ISSUE TITLE
Enable coupling when using static condensation through boundary conditions and traces

### ISSUE THREAD

**Issue by prudhomm** [feelpp/feelpp#1185]
we don't have coupling enabled with other problems when using static condensation. This is necessary for example when coupling traces to other problem types.
It requires:
 - enabling different kind of coupling patterns
 - supporting extra blocks for the coupled problems

the system after static condensation is laid out as follows:
 - First the blocks dealing with the condensed part 
 - Second the blocks associated to the coupling with other problems

**Comment by lsala** [comment]
@prudhomm to test the new static condensation:
`./feelpp_e2b_coupled-level1 --case eye2brain --case.config-file level1.cfg`

To run it, you need to compile:
`make feelpp_e2b_coupled-level1`
`make feelpp_add_testcase_eye2brain`
`make feelpp_add_fmu_retina_final`

For now it's impossible to run it with the github link since the fmu has be compiled

**Comment by lsala** [comment]
@prudhomm I made some progress for this issue, in particular now it is possible to run it (correctly) in monolithic. However it still doesn't converge with the static condensation and I suppose due to the fact it enters this function https://github.com/feelpp/feelpp/blob/6951af31016ff6bea86dd53c3170946d16156aeb/feel/feelalg/staticcondensation.hpp#L1498 that has not been defined yet

I'm not expecting that the program enters this function, now I will try to understand why.

Do you have any ideas? 

To test is is always:
`make feelpp_add_fmu_retina_final`
`make feelpp_add_testcase_eye2brain`
`make feelpp_e2b_main`

`./feelpp_e2b_main --config-file eye2brain/level1.cfg --mixedpoisson.use-sc=1`

**Comment by lsala** [comment]
No because in the case we're analysing we expect 5 spaces (3 standard + ibc + 0d)

**Comment by romainhild** [comment]
ok so the question is why does it enter the function that I linked. Which call `condense2` with a product space with 4 spaces.
