### ISSUE TITLE
Static condensation for HDG with IBC and ODE

### ISSUE THREAD

**Issue by lsala** [feelpp/feelpp#1297]
Allow the static condensation to work also with coupled ODE (with IBC condition)

Indeed there is an extra Ch space for every ODE added that has to be managed both for global and local solver.

Use of a dictionary when defining the space products in order to be able to identify ibc spaces and 0d spaces. 
The default behavior should be that any Ch space is an ibc one.

Work to do:
- adapt the current static condensation code to host a new Ch space (dynamic) that is different from the IBC
- create a test case similar to `hdg_laplacian_ibc`

**Comment by prudhomm** [comment]
I have been giving some more thoughts to this: we really need to identify the IBC from the ODE/AE spaces so the property system is a good idea. in static condensation we would now need an extra loop on faces which were not _attached_ to an element directly and associated to ODE/AE in order to add the corresponding equations set to the condensed system. 
Note that we could definitely extend this ODE/AE set on elements
