### ISSUE TITLE
`Statistics`: display value marker by marker when computed on a list of markers

### ISSUE THREAD

**Issue by Trophime** [feelpp/feelpp#1350]
Hi,
In `Statistics` It will be convenient to have a way to display value marker by marker when computed on a list of markers without having to declare an entry for each marker.

**Comment by vincentchabannes** [comment]
@Trophime since a653e08f47bb26f507d5e4fc872bf71f0d3f4168, 7639c49d421f0331d494758862d1ba4600931312
it should possible compute a Stat Measure for each markers with only one section.

I put the doc [here](http://docs.feelpp.org/toolboxes/0.107/what-is-a-toolbox/#_the_generator_of_cases_by_using_the_index_definitions)

**Comment by Trophime** [comment]
@vincentchabannes  as it works fine, I think we can close the issue ;)
