### ISSUE TITLE
add quickstart examples using Model classes 

### ISSUE THREAD

**Issue by prudhomm** [feelpp/feelpp#1481]
Model* classes allow to setup a model using json format.
they should be used in advanced quickstart cases 

/cc @thomas-saigre

**Comment by vincentchabannes** [comment]
@prudhomm please use features/toolboxes-refactoring branch

**Comment by prudhomm** [comment]
what do you mean ? I haven't finished the review, is there a particular feature I should use ?

**Comment by vincentchabannes** [comment]
and Model* class is designed mainly for the toolboxes, we don't want to rewrite all the toolboxes or I don't understand the idea of feel++ quickstart (for me it's already not quick to understand, it's quite advanced code and a very useful testsuite)

**Comment by vincentchabannes** [comment]
there are some changes (quite minor at this time) but many are planned because the design is not enough generic (particularly in BoundaryCondition). I don't want to maintain another part, it's already hard for me to manage (almost alone) the toolboxes.

**Comment by prudhomm** [comment]
not all quickstart examples will have this. only an example or two to examplify the use of Model as an advanced way to configure a PDE(configure BC and materials). Otherwise it will remain as it is with also much simpler examples.
I see 3 levels:
 - level 0 basic examples eg 10 lines laplacian
 - level 1 current examples 
 - level 2 more advanced models (eg like hygrotherly) using json (not toolboxes just a PDE configured in a flexible way) 

regarding level 2, the laplacian is underway

**Comment by vincentchabannes** [comment]
I done a lot of effort to write a generic pdes toolbox, the hygrothermal model can be almost taken into account (just a term missing and few things in the language, but it's planned and help will be welcome). 

But I think really quickstart it's not the good place or should be renamed.

**Comment by prudhomm** [comment]
renaming quickstart is a bit of work (debian ...)

I suggest to name it `gallery`

**Comment by prudhomm** [comment]
@vincentchabannes the code for the laplacian is quite simple I think see eg here 
bbadac6

**Comment by prudhomm** [comment]
the plan is to add documentation in the dev or user manual for this example to explain how to set BCV and material on complex geometries. I think it is not too complicated. What do you think ?

**Comment by vincentchabannes** [comment]
the problem for me is the dependency of ModelProperties. I try to explain that it's fully linked to feel++-toolboxes and it will be updated in a future quite soon. This kind of code will be broken probably.
We can just explain the structure of a property tree with boost, it's easy to read a json and it's also good exercise of C++, not just a copy past of this code.

For me, feelpp/feel/feelmodel/* should be moved in feelpp/toolboxes. And maybe we can write a small json tools for this quickstart

**Comment by prudhomm** [comment]
indeed this is a problem . the dependency is both ways between Model* and the toolboxes ? 
this means that some codes in subprojects will be  broken as well no ? 
I have to finish the review of the PR to understand what you mean. I am about half way

**Comment by metivett** [comment]
> renaming quickstart is a bit of work (debian ...)
> 
> I suggest to name it `gallery`

I think `gallery` would better refer to some simulation results than code samples; `examples` would be more expressive, no ? 
And regarding the Model* and toolbox interaction, I agree with @vincentchabannes that we should not mix too much the main lib utilities and the toolboxes' ones. However, the `Model*` classes in `feelpp/feel/feelmodels` are at the moment not so dependent on the toolboxes (the dependency is the other way round), so that maybe we should keep them like that (or even simplified) in the main `feelpp`, to provide a basic JSON parser (but then we should also provide more generic access, ie. this would only read some JSON, not provide subclasses like `ModelBoundaryConditions` and so on, the interpretation of the parsed info would be left to the user). And we could provide an enhanced (more specialised) JSON parsing support in `feelpp/toolboxes` with dedicated classes. 
From my experience, the situation is at the moment somehow inbetween and wobbly: we use the `feelpp/feel/feelmodels` within the toolboxes, but as they are not generic enough, you need to tweak them as soon as you want some non-basic thing.

**Comment by romainhild** [comment]
For me, the Model* classes should be generic enough to be used both in the toolboxes and outside.
I, for example, use them in my CRB apps, and in some of hifimagnet applications. So moving them into toolboxes is problematic.
I could just parse the JSON using boost, but then I would end up rewriting the Model* classes...

I think that whatever the toolboxes need from them, we should be able to accommodate in the other codes, and if they need to be updated when the toolboxes change, then we update the other codes...

Another solution would be to put in place a versioning of the ModelProperties. So that we could keep the json as they were when created but still change the way the json are parsed.

**Comment by vincentchabannes** [comment]
My idea is to gather all tools required by the toolboxes/model at the same place. and have a toolboxes-core quite fast to compile and of course can be used in external project as crb app.
Currently, it's a pain, some class Model* are in feelpp, others class Model* are in toolboxes.

And @prudhomm, currently there is no major change in API et json format, but It will be necessary. And I will start when the first part of this refactoring will be merged.

**Comment by prudhomm** [comment]
@thomas-saigre here is the command line for the model example:
you need to run the target `qs_add_testcase_cases`
```
./feelpp_qs_laplacian_model_2d --config-file cases/triangle/triangle.cfg --json_filename "\$cfgdir/triangle.json"
```
