### ISSUE TITLE
enabling/disabling submodels via json in multiphysic models

### ISSUE THREAD

**Issue by prudhomm** [feelpp/feelpp#1483]
it wxould be nice to enable/disable models in mutlphysics models via the json Model section.
we can set the equations
we could enable/disable like this. by default they would be enabled

```json
"Models": {
"heat":{   "enabled": 0 },
"moisture":{   "enabled": 1 }
}
```

maybe there is an alternative ?
/cc @vincentchabannes

**Comment by vincentchabannes** [comment]
@prudhomm In toolboxes, the `Models` section describe a pde/equation (and maybe submodel depending). The application of an equation (or Model) is done in `ModelMaterials` through the physics entry. The physics entry correspond to the name of the equation (or Model) and rely the mesh to an equation. I have not yet write the documentation of Models part but we can configure quite easily complex multiphysics models.

Note : In toolboxes, the ptree of ModelModels is given to specific class (Fluid/Solid/...) in order to setup specific properties. The structure can not be modified strongly.
Note about `use-model-name`: this entry disables by default allow to manage multiphysics. I think it is not very nice and I would prefer in future to put mandatory the model-name (correspond in fact to a toolbox) and remove this entry.
