### ISSUE TITLE
partitionnement on many cores not working when remeshing

### ISSUE THREAD

**Issue by thomas-saigre** [feelpp/feelpp#1880]
When I use `feelpp_mesh_partitionner` with `--remesh 1` and `--part 4` (with a number of partitions different of `1`), I get the following error message at the time of exporting the mesh
```
      number of marked faces Retina_VitreousHumor with tag 34 : 51
===================[ export mesh ]===================
zsh: segmentation fault (core dumped)  feelpp_mesh_partitioner --ifile $PWD/Eye_Mesh0.msh --odir $PWD/remesh --part 
```
There is no more explication in the shell, neither in the `log` directory

On way to by-pass this problem is to remesh the original mesh, with one partition, then rerun  `feelpp_mesh_partitionner` without remeshing and export on many parts, but it doesn't "cancel" the issue !

**Comment by vincentchabannes** [comment]
The remesher is not the goal of `feelpp_mesh_partitionner`, I am quite surprised that there is a remesh option. Moreover, some properties allow to read the mesh faster (or large meshes) but can't apply a correct remesh (because missing entity/mesh data) @prudhomm.
A specific app for a remesher should be added (if not exist). Anyway, this should be in two steps: first remesh, then partitioning

**Comment by thomas-saigre** [comment]
Has this issue been fixed ? I tried today to run the same command as described above, I get the same export MET=error in the end.
Running remeshing first, then partitioning works well, but is more costly because we have to run the application and load the mesh twice
