### ISSUE TITLE
feelpp 0.110.0~rc.4: execs return wrong version number

### ISSUE THREAD

**Issue by Trophime** [feelpp/feelpp#1920]
Hi,
in latest feelpp ubuntu packages, executables return a wrong version:

```
 feelpp_mesh_partitioner --version
No protocol specified
Error   : Unknown number option 'General.NativeFileChooser'
mesh_partitioner: Feel++ application
 version : Feel::Info::versionString()
```

**Comment by thomas-saigre** [comment]
I also found this issue in the late months. I found that is it because in [about.hpp#L519](https://github.com/feelpp/feelpp/blob/develop/feelpp/feel/feelcore/about.hpp#L519), `Feel::Info::versionString` is in quotes.
I made a commit (1e54620faf58e5e32d2edf37e6963bc27fe9020a) in another branch to fix this, the pull request #1917 waits to be validated. I will link this issue to the corresponding pull request so it will be closed automatically if it is merged
(/cc @prudhomm we can also cherry pick the commit if needed)
