### ISSUE TITLE
nirb in parallel

### ISSUE THREAD

**Issue by thomas-saigre** [feelpp/feelpp#1952]

**Comment by alielarif** [comment]
- [ ] remove all the creation of matrix with petsc4py 
- [ ] gather all the basis functions in a python list and save them in separate files (hdf5 format in preference). 

By doing that, we constate the following problems : 
- the clone function, creates a new vector instead of copying it for petsc vectors. However, it does the copy for the other types. 
- the addVector function works well only for petsc vectors. For other types, it adds a null vector

**Comment by alielarif** [comment]
> what does that mean ? it does the copy for the other types. ?
For ublas vector type and discrete element, the clone fonction does the copy of it. But for petsc vector, it create a new one. 
When I looked at the clone function in  "feel/feelalg/vectorpetsc.cpp", the line that should do the copy was commented (line 66). I thought there should be a reason to do it.

> you need to check the interface in c++ 
I check that in "feel/feelalg/vectorublas.cpp" (line 546), but it is returned that the function is not implmented yet. What's strange is that I don't get an error message when calling the function.
