### ISSUE TITLE
Memory allocation for linear and bilinear forms behave differently

### ISSUE THREAD

**Issue by lberti** [feelpp/feelpp#2049]
In the case of linear forms, if memory is already allocated, it should not be re-allocated.

For bilinear forms, this is already the case.

**Comment by prudhomm** [comment]
The issue is indeed that bilinear and linear forms do not behave the same way wrt `operator=`.
bilinear forms do not reallocate memory of underlying algebraic representation if it is already allocated whereas linear forms do. This is a problem for example in non-linear solvers where the residual vector is passed to the linear form: it should not be reallocated if we use `operator=` for example to initialize with the linear part of the residual.
