### ISSUE TITLE
Suggestion on an alternative place for user discussion

### ISSUE THREAD

**Issue by grabbitnu** [feelpp/feelpp#493]
Dear all,

As a beginner, I have to say the group of Feel++ on Google are not accessible for lots of users from China, due to political reasons. So,  is it possible to open an alternative site for open discussion on usage and helps of FeelPP? Or may we just post here?

Many thanks.

Zhenyu

**Comment by grabbitnu** [comment]
Forgive me but there's no link for registering feelpp-user@feelpp.org at http://www.feelpp.org/community

**Comment by prudhomm** [comment]
@grabbitnu you click on Feel++ Users link and ask to join the group.
Since it is the google group service, may be it is blocked too ?

look at the image below that shows the "join group" button
![screen shot 2015-01-04 at 08 44 22](https://cloud.githubusercontent.com/assets/151693/5605200/035264a6-93ee-11e4-9d49-aea44cd478bc.png)

**Comment by grabbitnu** [comment]
The link is definitely blocked. I am sorry to say that. Anyway, thank you very much for your kind help.
Zhenyu

**Comment by vhuber** [comment]
We should try to manually add your e-mail, isn't it ?

**Comment by grabbitnu** [comment]
Thank you first. If you can, here is my email: zyzhang@nuaa.edu.cn.
