### ISSUE TITLE
wikipedia

### ISSUE THREAD

**Issue by vhuber** [feelpp/feelpp#530]
- [x] http://fr.wikipedia.org/wiki/Feel%2B%2B : wrong link at the end
- [ ] http://en.wikipedia.org/wiki/List_of_finite_element_software_packages : Feel++ is not listed

**Comment by prudhomm** [comment]
actually the fr.wikipedia is due to @gdolle

**Comment by prudhomm** [comment]
and he also looked into the english pages

**Comment by gdolle** [comment]
Yes indeed.
The time I wrote on the english wiki, they removed the page saying that
Feel++ didn't have enough notoriety to have its own page (Wikipedia rules).
The discussion is available on the page
http://en.wikipedia.org/wiki/Feel%2B%2B
It seems they've also removed it from the list of software.

I will fix links on the french wiki page, maybe adding more references
wouldn't be a bad idea too.
Any contribution on the wiki is welcome.
(It would even be better if wiki contributors are external from the Feel++
core team)

2015-02-13 15:38 GMT+01:00 prudhomm <notifications@github.com>:

**Comment by gdolle** [comment]
- [x] fix wrong link
- [ ]  add in list of elements softwares (en wiki). Anyway it is available on the french wiki, see here:
https://fr.wikipedia.org/wiki/Cat%C3%A9gorie:Logiciel_de_calcul_num%C3%A9rique

**Comment by prudhomm** [comment]
5 thanks a lot!  :+1:

**Comment by vhuber** [comment]
@gdolle is there any improvements about that issue at this time ?

**Comment by gdolle** [comment]
Since my last message, I fixed links and added some references in the
french wiki only.
Feel++ is listed on the french computation software list (
http://fr.wikipedia.org/wiki/Cat%C3%A9gorie:Logiciel_de_calcul_num%C3%A9rique
)

I did not try to propose again the Feel++ page on the english wiki. (Note
that it was automatically removed from the english FEM software list when
the page was removed).


2015-03-30 14:52 GMT+02:00 Vincent Huber <notifications@github.com>:
