### ISSUE TITLE
Bug in handling face dof in vectorial finite elements (e.g. Nedelec,RT)

### ISSUE THREAD

**Issue by vhuber** [feelpp/feelpp#544]
On a Nedelec space, dof (that are vectors) are located on the face/edges in 2D/3D.

On a 2D test, with 5 boundary edges, 6 entry in the matrix are modified.

For convergence tests, there are no way to see it, as long as the exact solution is provided to an extra dof.

DVLOG indicates that a face had two dofs, and each times the second one has the global number 0.

**Comment by vhuber** [comment]
0553702a8c687cb951b759a77381e2ad0e1f17c6

**Comment by cdaversin** [comment]
The table `M_face_l2g` links local/global indices of face dofs. 
It is used by `on` function to impose strong Dirichlet condition with finite elements having dofs on faces (Nedelec), to identify which are the matrix elements to change.

This table was resized with the product of number of dofs per face (1 in this case) by the number of components (which was the dimension, 2 in this case), but only one element of `M_face_l2g` was filled since there is only one dof per face.

The second component of `M_face_l2g` was not initialized (it contained 0), and implied the modification of the matrix row associated with dof of global number 0 (see previous comment)

**Comment by prudhomm** [comment]
Nice catch

**Comment by prudhomm** [comment]
I now close the issue
