### ISSUE TITLE
Add support for ExtendedFieldFromInterface 

### ISSUE THREAD

**Issue by prudhomm** [feelpp/feelpp#610]
Add a class to build an extended field from its value defined at an interface typically given by a levelset function. It was proposed in @Doyeux Phd thesis.
By the way @Doyeux I still have to mvoe the levelset code from fsi to Feel++. 
/cc @VANTHONG @Doyeux

**Comment by Doyeux** [comment]
There were a poor tentative to do that in the level set repo. Is that the one you took to implement this class?
I say it's "poor" because it's doing the very simple O(N^2) algorithm. It checks for every dof the closest dof of the interface.
I was thinking, during the fast marching, we could keep for each node, the information of the closest node of the interface used to generate its distance function. Basically at the end, we will obtain a Voronoi diagram where the points would be the nodes initially on the interface, and the zones would be all the closest points to it.
From there, it would be really easy to create the extended velocity: just assign to each zone the value of the velocity of the Voronoi point of the zone.
This might be used in other context, like answering the question: for every point in the domain, which is the closest point on the boundary.
The algo should be in O(n log N) as the fast marching.
This should be too hard to implement add to the fast marching class.

**Comment by prudhomm** [comment]
I saw the O(N^2) part but we need it fast. We will see afterwards. It should be too difficult to optimize that ;)

**Comment by Doyeux** [comment]
Ok, I don't know when I'll have time to make the changes in fast marching to enable the O(n log n) method. I'm leaving for a month starting from monday.

I just found two videos I saved using the extended velocity for contour detection. I uploaded it, so that you have an idea what to expect:
https://youtu.be/gZih98-pOkU
https://youtu.be/8ZHsl4KYQYU

**Comment by Doyeux** [comment]
Also, the O(N^2) method should be too hard to make parallel. If the information of the dof being in the interface are broadcast to all the processors, each processor can create its own field. Thus the method should have an acceleration with respect to the number of proc (at the opposite of the marching, which is O(n ln n) but without acceleration).
