### ISSUE TITLE
Support GMSH geometry Include keyword

### ISSUE THREAD

**Issue by gdolle** [feelpp/feelpp#631]
Currently, it seems that the Feel++ GMSH parser does not support `Include` keywords
in GMSH geometry files.

An idea could be to replace the `Include "toto.geo";` line by the content of `toto.geo`.

**Comment by prudhomm** [comment]
what do you mean by 

> the Feel++ GMSH parser does not support Include keywords
in GMSH geometry files

?

**Comment by gdolle** [comment]
To be more precise, you can create a geometry from several files using the
`Include` keywords.

```
// file1.geo
h=0.1;
Include "file2.geo";
```

```
// file2.geo
Point(1) = {0,0,0,h};
```

Of course you have to think to add the two .geo files in the CMakeList.txt.

- If you use "file1.geo" with feel++, it will break because the current
parser parse only the file1.geo. So only "file1.geo" is written in the
WORKDIR.
A solution would be to do a copy of "file2.geo" in the working directory.

- A second problem that I see is that you have to add all variables in
"file1.geo" to be correctly parsed in feel++ as a parameter that can be
changed though the option (`--gmsh.geo-variable-list`).

I think we can keep this issue as a feature as most user don't use this
GMSH feature with feel++.



2015-08-16 22:23 GMT+02:00 prudhomm <notifications@github.com>:

**Comment by prudhomm** [comment]
yes it would be a feature. it is not an issue

**Comment by vhuber** [comment]
@gdolle Here a solution
- use `Include "$home/myCode/file2.geo"` in `file1.geo` (or whatever variable you want)
- with boost.regex find every line that contains `Include`
- parse theses lines with `Environnment::expand` get the full path (instead of `$home`).
Normally, Gmsh will look at your included file correctly.

We can also avoid the use of variable to keep the system coherent and specify that every `Include file.geo` has to be replaced with `Include /where/I/run/my/code/file.geo`.

**Comment by cdaversin** [comment]
@gdolle Have you tried to use ````Merge```` gmsh keyword instead of ````Include````  in your ````.geo```` file ? Combined with the use of ````gmsh.depends```` option which copy the needed additional files in the current directory
