### ISSUE TITLE
Geometry file parse variable bug

### ISSUE THREAD

**Issue by gdolle** [feelpp/feelpp#634]
If the geometry contains a variable with underscore, the wrong variable might be replace when passing some option, for example

```
h=0.1;
myvar_h=0;
```
If you pass the option `--gmsh.hsize=0.5` will give
```
h=0.5;
myvar_h=0.5;
```

**Comment by vhuber** [comment]
@gdolle 
That is not due to the underscore (try it with `myvarh=0;`).
That is - I guess - because the regex does not indicates "the beginning of the line".
To do so, you have to begin the regex with `^`.
I'm pretty sure you face the same problem with your `geo-variables-list` option (so the following commit will modify it)
