### ISSUE TITLE
Design issue in Biosavart RB

### ISSUE THREAD

**Issue by prudhomm** [feelpp/feelpp#949]
Biosavart does both reduced order algorithm like CRB plus the model part. This is not good. It need to be split.
I propose to have the algorithmic part in `feel/feelcrb` and the model part moved to `application/crb/thermoelectric/` to be consistent.

- [x] split algo and model
- [x] use databases to store basis
- [ ] use crbdb to store reduced quantities
- [x] compute rb field
- [x] compute fe field
- [ ] add outputs
- [ ] add SER like algo

**Comment by prudhomm** [comment]
Once this is fixed, I think the integration as the CRBPlugin will be easy. 
`BiosavartRB` (`feel/feelcrb/biosavartrb.hpp`) is going to be a subclass of `CRB` like `CRBTrilinear` and offer the proper interface to be used online with an associated model

**Comment by romainhild** [comment]
@vincentchabannes Could we have a `CRBPluginBase` class to use as `AlgoBaseT` here https://github.com/feelpp/feelpp/blob/d733bac1a6e8e1cafd74e4599bec9e33c0bca0e5/feel/feelcrb/crbplugin.hpp#L109
Then CRB, CRBSaddlePoint, CRBTrilinear and BiotSavart would inherit from it.

It should have the following methods:
- loadDB(filename, crb::load)
- loadDBFromId(id, crb::load, root)
- loadDBLast(crb::last, crb::last, root)
- Dmu()
- model()
- run(mu, t, eps, N, print_rb_matrix)
- run( mus, eps, N, print_rb_matrix)

The first three methods would be inherited from CRBDB.
The model() method should return an object which have a `rBFunctionSpace()` method.

So we would have 
```
CRBDB
   \
 CRBPluginBase    CRBBase
             \     /
               CRB
```
Then we wouldn't need AlgoBaseT anymore, it would always be CRBPluginBase. And it would be easier to add a new algorithm.

**Comment by romainhild** [comment]
@Trophime @prudhomm @vincentchabannes I pushed a first version of Biotsavart using the databases, see bd70b12, can you look to see if something is wrong ?

I still need to add some outputs, for now it only computes the magnetic field.
For this, @Trophime what would we need for the identification of parameters ?
Also, @prudhomm is it possible to have the min/max of the field as an output ?

I also thought about an algorithm like SER to compute the basis, since the number of basis can grow quickly, it could be quite costly to compute the basis.
For example, if we have two materials in the conductor, each need an EIM basis for sigma, say 10 basis each, and CRB itself with 10 basis. then the number of BiotSavart basis to compute would be of 200...
I wrote it, I'll try to implement it next week once I'm sure BiotSavart works correctly.

**Comment by prudhomm** [comment]
@romainhild we did not go further in the discussion. where are we now on this front ?

**Comment by romainhild** [comment]
I'll run the code and see where we are, but the redesign was done [here](https://github.com/feelpp/feelpp/blob/develop/feelpp/feel/feelcrb/biotsavartrb.hpp).

**Comment by romainhild** [comment]
This issue can be close.
